### ISSUE TITLE
README, makefile and dependecies

### ISSUE THREAD

**Issue by lyle-univ** [Regan-Koopmans/NavUP-Broadsword#7]
Hi guys, this is the data team. I thought I would drop a message here regarding scripts we set up to make it a bit easier for you guys to integrate our subsystem.

For the documentation, there is a mock main.tex, but that is just to check that everything compiles. There is a makefile for the documentation that compiles the diagrams that are included in the latex section of our subsystem. The software dependency(Umlet) can be satisfied by running `make dependency`. The document can be compiled by running `make pdf` and if you just want to compile the diagrams run `make diagrams`.

To satisfy the few software dependencies that there are for the system, run `./integration_setup.sh`.

Lastly, the entry point to the system is query\_resolver.py. If you run `query_resolver.py -h`, it will print out the program parameters that need filling in for the system to function as expected. These parameters include the NSQ server location, port number and Aruba credentials to name a few.

Hope this helps
Cheers
Data Team

**Comment by Regan-Koopmans** [comment]
Thanks Lyle, really appreciate it! :smiley:
